### PR TITLE
Removed fixed string inside Identifier Strategy + minor refactors

### LINKED ISSUE #2: [Bug ] Fixing override of data product fqn when parsing
Fixing override of data product fully qualified name when parsing a data product descriptor.

### PR DESCRIPTION
**Pull request by gabrielefantini**

### CODE REVIEW

File: src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategy.java
Comment (gabrielefantini) [inline src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategy.java:1]: Refactored into an interface with the following methods (which are used inside ODM platform)
- String getId(String fqn);
- String getFqn(DataProductVersionDPDS descriptor, ComponentDPDS component);
- String getExternalComponentFqn(
            EntityTypeDPDS type,
            String name,
            String version);

File: src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategyDefault.java
Comment (gabrielefantini) [inline src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategyDefault.java:1]: Package private class. Implementation details are not exposed outside.

File: src/main/java/org/opendatamesh/dpds/parser/ParseOptions.java
Comment (gabrielefantini) [inline src/main/java/org/opendatamesh/dpds/parser/ParseOptions.java:1]: Dangerous refactor but the renamed field are not used in ODM platform yet.

File: src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategy.java [hunk 1]
```diff
@@ -1,183 +1,17 @@
...
-import org.apache.commons.lang3.StringUtils;
 import org.opendatamesh.dpds.model.DataProductVersionDPDS;
 import org.opendatamesh.dpds.model.core.ComponentDPDS;
 import org.opendatamesh.dpds.model.core.EntityTypeDPDS;
-import org.opendatamesh.dpds.model.core.StandardDefinitionDPDS;
-import org.opendatamesh.dpds.model.info.InfoDPDS;
 
-import java.util.Objects;
-import java.util.UUID;
+public interface IdentifierStrategy {
```
Comment (gabrielefantini) [inline src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategy.java:11]: add javadoc

File: src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategyFactory.java [hunk 2]
```diff
@@ -0,0 +1,11 @@
+package org.opendatamesh.dpds.parser;
+
+public abstract class IdentifierStrategyFactory {
+    private IdentifierStrategyFactory() {
+
+    }
+
+    public static IdentifierStrategy getDefault(String organization) {
+        return new IdentifierStrategyDefault(organization);
```
Comment (gabrielefantini) [inline src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategyFactory.java:33]: add method to allow null org

File: src/main/java/org/opendatamesh/dpds/processors/ReadOnlyPropertiesProcessor.java [hunk 3]
```diff
@@ -96,7 +96,7 @@ private void addReadOnlyPropertiesToInfo() throws DeserializationException {
 
         // Rewrite "fqn"
         try {
-            fqn = context.getOptions().getIdentifierStrategy().getFqn(descriptor);
+            fqn = context.getOptions().getIdentifierStrategy().getFqn(descriptor, null);
```
Comment (gabrielefantini) [inline src/main/java/org/opendatamesh/dpds/processors/ReadOnlyPropertiesProcessor.java]: keep overloading on interface

File: src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategyFactory.java [hunk 4]
```diff
@@ -0,0 +1,11 @@
+package org.opendatamesh.dpds.parser;
+
+public abstract class IdentifierStrategyFactory {
```
Comment (gabrielefantini) [inline src/main/java/org/opendatamesh/dpds/parser/IdentifierStrategyFactory.java:8]: Add javadoc
